### ISSUE TITLE
无效的链接！Invalid link!

### ISSUE THREAD

**Issue by winic57** [SaltyLeo/i-book.in_Archive#2]
点击“点击此处从IPFS网关下载”出现错误
http://127.0.0.1:7743/ipfsd?d=d349f1c701ff48c1bff9d95859049e22&l=zh

无效的链接！Invalid link!

不知道为什么，这个链接无效。请使用其他关键词重新搜索或 点此 查看使用帮助。

**Comment by SaltyLeo** [comment]
这只是个框架，里面的索引数据只有两条，并且没有有效下载链接，请按照【test.json】类似的格式，编辑并添加有效索引。

我再重申一下，这只是个【框架】。没有任何有效数据。
