### ISSUE TITLE
搜索没有任何结果

### ISSUE THREAD

**Issue by Ryde-L** [SaltyLeo/i-book.in_Archive#4]
按流程走也没有报错，请问是已经失效了么

**Comment by Light-Towers** [comment]
> 按流程走也没有报错，请问是已经失效了么

@Ryde-L 请问后来解决了吗？可以搜到结果了吗？

**Comment by SaltyLeo** [comment]
> > 按流程走也没有报错，请问是已经失效了么
> 
> @Ryde-L 请问后来解决了吗？可以搜到结果了吗？

这只是个框架....
